### PR TITLE
github issue #1 : adding logging in for all the packages and applicat…

### PR DESCRIPTION
**Pull request by jon-shanks**
…ions

### CODE REVIEW

**Comment by timgent** [comment]
132 files changed?? I've not used go but is there not a way to manage those kinds of dependencies?

**Comment by jon-shanks** [comment]
I believe the pattern is you pull down your dependencies so you have a working piece of code nailed to specific elements in your vendor packages, so you can guarantee the consistency. you don't need to really care potentially about what is in vendor more what is in src. We need tests, but there is an issue for that and i will start working on them over next week.

**Comment by vaijab** [comment]
> but is there not a way to manage those kinds of dependencies?

@timgent that's one way of managing them by vendoring them in.

**Comment by jon-shanks** [comment]
@vaijab : i do if you look at the change ;-) you can see me adding it into .gitignore

**Comment by vaijab** [comment]
> i do if you look at the change

@jon-shanks I meant a real global one in your `${HOME}`.

```
cat ~/.gitignore 
*.swp
*.class
*.dll
*.exe
*.o
*.so
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip
*.pyc
.ropeproject
.DS_Store
```

**Comment by jon-shanks** [comment]
Ah i do, but it got removed when i cleaned up my mac and i never repopulated it, (which was a while ago to be fair)

core.excludesfile=/Users/jshanks/.gitignore_global

is in my git config ;-) but the file wasn't there, added it in the repo just incase others do it anyway as a lot of people are on a mac.

**Comment by jon-shanks** [comment]
That aside, we happy to merge?

**Comment by vaijab** [comment]
@jon-shanks LGTM, go ahead and merge it when you're happy.

**Pull request merged**
